In [2]:
!pip install numpy


In [3]:
import numpy as np

In [4]:
dizi = np.array([1,5,9])
print(dizi)

[1 5 9]


In [5]:
dizi2= np.array([1,5,7,5,8,7,15,9,44,18,12,25,14,39])
print(dizi2.shape)
bol = dizi2.reshape(2,7) 
print(bol)
print("shape: ",bol.shape) 
print("dimension: ",bol.ndim) 
print("data type: ",bol.dtype.name) 
print("size: ",bol.size) 
print("type",type(bol))

(14,)
[[ 1  5  7  5  8  7 15]
 [ 9 44 18 12 25 14 39]]
shape:  (2, 7)
dimension:  2
data type:  int32
size:  14
type <class 'numpy.ndarray'>


In [6]:
dizi3= np.array([[ 1,5,7,5,8,7,15],[9,44,18,12,25,14,39]])
print(dizi3)
print(dizi3.shape)


[[ 1  5  7  5  8  7 15]
 [ 9 44 18 12 25 14 39]]
(2, 7)


In [7]:
dizi4= np.zeros((3,4))
dizi4[0,0]=1
print(dizi4)

[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
dizi5=np.ones((3,4))
print(dizi5)
dizi6=np.empty((4,5))
print(dizi6)
dizi6=np.arange(100,1000,100)
print(dizi6)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.33512376e-306
  1.89146896e-307]
 [7.56571288e-307 3.11525958e-307 1.24610723e-306 1.37962320e-306
  1.29060871e-306]
 [2.22518251e-306 1.33511969e-306 1.78022342e-306 1.05700345e-307
  3.11525958e-307]
 [1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306
  1.29062229e-306]]
[100 200 300 400 500 600 700 800 900]


In [18]:
dizi7= np.linspace(0,10,30)
print(dizi7)
dizi8= np.array([5,7,9])
dizi9= np.array([1,3,5])
print(dizi8+dizi9) 
print(dizi8-dizi9) 
print(dizi8**2) 
list1 = [1,2,3,4]
dizi10 = np.array([5,6,7,8])
print(list1)
print(dizi10)
dizi11 = np.array(list1)
print(dizi11)
liste2 = dizi11.tolist()
print(liste2)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]
[ 6 10 14]
[4 4 4]
[25 49 81]
[1, 2, 3, 4]
[5 6 7 8]
[1 2 3 4]
[1, 2, 3, 4]


In [22]:
a = np.array([1,2,3])
print(a)
b=a
c=a
c[1]=8 
print(a,b,c)

[1 2 3]
[1 8 3] [1 8 3] [1 8 3]


In [24]:
d = a.copy()
print(d)

[1 8 3]


In [27]:
dizi12= np.array([1,3,5,9,11,13,15])
print(dizi12)
print(dizi12[0])
print(dizi12[0:4])
reverse_array = dizi12[::-1]
print(reverse_array)

[ 1  3  5  9 11 13 15]
1
[1 3 5 9]
[15 13 11  9  5  3  1]


In [28]:
b = np.array([[1,3,5,7,9],[11,13,15,19,21]]) 
print(b)

[[ 1  3  5  7  9]
 [11 13 15 19 21]]


In [29]:
print(b[3,3]) 
print(b[:,1]) 
print(b[1,:]) 
print(b[1,1:4]) 
print(b[-1,:])
print(b[:,-1])

13
[ 3 13]
[11 13 15 19 21]
[13 15 19]
[11 13 15 19 21]
[ 9 21]


In [30]:
array1 = np.array([[1,3,5],[7,9,11],[13,15,17]])
print(array1)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [31]:
array1ravel = array1.ravel()
print(array1ravel)

[ 1  3  5  7  9 11 13 15 17]


In [32]:
array2 = array1ravel.reshape(3,3) 
print(array2)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [33]:
array_transpose = array2.T
print(array_transpose)

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [34]:
array3 = np.array([[1,3],[5,7],[9,11]])
print(array3)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [36]:
array3.resize((1,6)) 
print(array3)

[[ 1  3  5  7  9 11]]
